export interface Strategy {
  id: number;
  account_id: number;
  name: string;
  direction: 'long' | 'short';
  symbol: string | null;
  signal_source: 'rsi' | 'wavetrend';
  rsi_period: number;
  timeframe: string;
  wt_channel_length: number;
  wt_average_length: number;
  margin_threshold: number;
  base_qty_type: 'margin_pct' | 'usdt';
  base_qty_value: number;
  rsi_entry_threshold: number;
  price_drop_pct: number;
  martingale_mult: number;
  max_layers: number;
  martingale_rsi_enabled: boolean;
  take_profit_pct: number;
  take_profit_limit_order: boolean;
  stop_loss_enabled: boolean;
  stop_loss_pct: number;
  slippage_pct: number;
  leverage: number;
  use_coin_pool: boolean;
  coin_pool_source: 'gainers' | 'losers' | 'both';
  coin_pool_refresh_seconds: number;
  coin_pool_fetch_mode: 'immediate' | 'interval';
  coin_pool_top_n: number;
  status: 'running' | 'stopped' | 'error';
  started_at: string | null;
  last_rsi: number | null;
  last_signal: string | null;
  last_signal_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface StrategyFormData {
  account_id: number;
  name: string;
  direction: 'long' | 'short';
  symbol?: string;
  signal_source: 'rsi' | 'wavetrend';
  rsi_period: number;
  timeframe: string;
  wt_channel_length: number;
  wt_average_length: number;
  margin_threshold: number;
  base_qty_type: 'margin_pct' | 'usdt';
  base_qty_value: number;
  rsi_entry_threshold: number;
  price_drop_pct: number;
  martingale_mult: number;
  max_layers: number;
  martingale_rsi_enabled: boolean;
  take_profit_pct: number;
  take_profit_limit_order: boolean;
  stop_loss_enabled: boolean;
  stop_loss_pct: number;
  slippage_pct: number;
  leverage: number;
  use_coin_pool: boolean;
  coin_pool_source: 'gainers' | 'losers' | 'both';
  coin_pool_refresh_seconds: number;
  coin_pool_fetch_mode: 'immediate' | 'interval';
  coin_pool_top_n: number;
}
