"""add_wavetrend

Revision ID: 27ebbddc1f54
Revises: a3299cd5d86d
Create Date: 2026-05-04 17:59:57.313203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ebbddc1f54'
down_revision: Union[str, Sequence[str], None] = 'a3299cd5d86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if 'strategies' in insp.get_table_names():
        cols = [c['name'] for c in insp.get_columns('strategies')]
        if 'signal_source' not in cols:
            op.add_column('strategies', sa.Column('signal_source', sa.String(length=20), server_default='rsi', nullable=False))
        if 'wt_channel_length' not in cols:
            op.add_column('strategies', sa.Column('wt_channel_length', sa.Integer(), server_default='10', nullable=False))
        if 'wt_average_length' not in cols:
            op.add_column('strategies', sa.Column('wt_average_length', sa.Integer(), server_default='21', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'wt_average_length')
    op.drop_column('strategies', 'wt_channel_length')
    op.drop_column('strategies', 'signal_source')
    # ### end Alembic commands ###
