"""add_account_hedge_mode

Revision ID: 587e25f3f1d6
Revises: 27ebbddc1f54
Create Date: 2026-05-06 00:11:19.326323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587e25f3f1d6'
down_revision: Union[str, Sequence[str], None] = '27ebbddc1f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('hedge_mode', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'hedge_mode')
    # ### end Alembic commands ###
