"""initial

Revision ID: 8f805466b71c
Revises: 
Create Date: 2026-05-03 19:26:08.688288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f805466b71c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'run_interval_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('run_interval_seconds', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
