"""add_coin_pool_top_n

Revision ID: 96fcf209e656
Revises: 587e25f3f1d6
Create Date: 2026-05-06 16:27:20.863574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fcf209e656'
down_revision: Union[str, Sequence[str], None] = '587e25f3f1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if 'strategies' in insp.get_table_names():
        cols = [c['name'] for c in insp.get_columns('strategies')]
        if 'coin_pool_top_n' not in cols:
            op.add_column('strategies', sa.Column('coin_pool_top_n', sa.Integer(), nullable=False, server_default='20'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'coin_pool_top_n')
    # ### end Alembic commands ###
