"""add_martingale_rsi_enabled

Revision ID: a3299cd5d86d
Revises: 8f805466b71c
Create Date: 2026-05-04 16:58:00.771552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3299cd5d86d'
down_revision: Union[str, Sequence[str], None] = '8f805466b71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if 'strategies' in insp.get_table_names():
        cols = [c['name'] for c in insp.get_columns('strategies')]
        if 'martingale_rsi_enabled' not in cols:
            op.add_column('strategies', sa.Column('martingale_rsi_enabled', sa.Boolean(), server_default='0', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'martingale_rsi_enabled')
    # ### end Alembic commands ###
